name: Build for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decode Android keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          test -n "$KEYSTORE_BASE64"
          echo "$KEYSTORE_BASE64" | base64 --decode > refilc/android/upload-keystore.jks

      - name: Create key.properties
        run: |
          cat > refilc/android/key.properties <<EOF
          storeFile=${{ github.workspace }}/refilc/android/upload-keystore.jks
          storePassword=${{ secrets.STORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          EOF

      - name: Create debugkey.properties
        run: |
          cat > refilc/android/debugkey.properties <<EOF
          storeFile=${{ github.workspace }}/refilc/android/upload-keystore.jks
          storePassword=${{ secrets.STORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          EOF

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
          channel: stable
          cache: true

      - name: Install dependencies
        run: bash ./fix-pub.sh

      - name: Build Android APK
        run: |
          cd refilc
          bash ./build.sh

      - name: Upload Android Release
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: refilc/build/outputs/flutter-apk/ekrata-ellenorzo-release.apk